#!/bin/sh
TODAY=`date '+%d-%m-%Y'`
WIPBACKUPPATH=/opt/webin/BACKUP/WIP_BKUP;
WEBINBACKUPPATH=/opt/webin/BACKUP/WEBIN_BKUP;
WEBINFBACKUPPATH=/opt/webin/BACKUP/WEBINF_BKUP;
TOMCATBACKUPPATH=/opt/webin/BACKUP/TOMCAT_BKUP;
SCRIPTBACKUPPATH=/opt/webin/BACKUP/SCRIPT_BKUP;

cd /opt/webin;
tar -zcvf $WIPBACKUPPATH/WIP-$TODAY.tar.gz WIP/
tar -zcvf $WEBINBACKUPPATH/WEBIN-$TODAY.tar.gz WEBIN/
tar -zcvf $TOMCATBACKUPPATH/TOMCAT-$TODAY.tar.gz TOMCAT/


cd /opt/webin/WEBIN
tar -zcvf $WEBINFBACKUPPATH/WEBINF-$TODAY.tar.gz WEB-INF/
tar -zcvf $SCRIPTBACKUPPATH/SCRIPT-$TODAY.tar.gz scripts/
