DAY=`date +%Y%m%d`;
log=/u01/COL_HC/Report/;
sed -i s/MUMAIRvCGN/MUM-VPCNEW/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIGJ02AH/Ahmadabad-VPC/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIKL08PA/PALAKKAD/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/AHDSGHCGNA/AHD-BM/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/invirj18jp/JAIPUR-IBM/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/AHDSGHCGNA/AHD-BM/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIKO22KO/Jabalpur/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIGJ02GN/Gandhinagar/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIGJ02RJ/RajkotIBM/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/SURUMACGNA/Surat/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/RAJKOTCGNA/Rajkot/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/mpybplcgn0/Bhopal/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIMP03RP/Raipur/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/delokhcgn/Okhla/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/DELYAMCGNA/Delhi/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/DELYAMCGNA/Delhi/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/GRGUDYCGNA/DELVPC/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/GRGUDYCGNA/DELVPC/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/DELNARCGNA/Narayana/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/CALCUTCGNA/Calicut/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/coherncgna/COCHIN/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIKL08KL/Kollam/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIKL08PL/pallakad/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/GUWKATCGNA/Guwahati/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/GUWKATCGNA/Guwahati/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/KOLAGRCGNA/KOL-BM-Cisco/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/KOLAGRCGNA/KOL-BM-Cisco/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/inviko22ko/Kolkata-BIO/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/LUKASMCGNA/LKO-Cisco/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/LUKASMCGNA/LKO-Cisco/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/AGRTORCGNA/Agra/g         ${log}Brief_${DAY}_PendingCount.csv
sed -i s/mahnskcgn0/Nashik/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/JAIMANCGNA/Jaipur/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/JAIMANCGNA/Jaipur/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/RAJJAIVCGC/JaipurEIL/g      ${log}Brief_${DAY}_PendingCount.csv
sed -i s/PUNMOHVCGC/MohaliEIL/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIPB07LD/LudhianaEIL/g     ${log}Brief_${DAY}_PendingCount.csv
sed -i s/HARKARVCGC/KarnalEIL/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIHR11SN/SonipatEIL/g      ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIRJ18KT/KotputliEIL/g     ${log}Brief_${DAY}_PendingCount.csv
sed -i s/DELOKHCGN/Okhla/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/RAJJODVCGC/JodhpurEIL/g      ${log}Brief_${DAY}_PendingCount.csv
sed -i s/MAHNAGVCGC/NagpurEIL/g       ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIMH01KL/KolhapurEIL/g     ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIMH01SL/SolapurEIL/g      ${log}Brief_${DAY}_PendingCount.csv
sed -i s/mahkalecl0/Pune1EIL/g        ${log}Brief_${DAY}_PendingCount.csv
sed -i s/MAHKALVCGC/Pune2EIL/g        ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVIOR15BS/BhubaneshwarEIL/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/CHNEKTCGNA/CHN1/g         ${log}Brief_${DAY}_PendingCount.csv
sed -i s/INVITN14CH/CHN-SIRUSERI/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/CHNNXTCGNA/CHN2/g         ${log}Brief_${DAY}_PendingCount.csv
sed -i s/MUMAIRVCGN/Mumbai-VPC1/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/MUMARLCGNA/Mumbai-BM/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/mumaircgna/Mumbai-VPC2/g    ${log}Brief_${DAY}_PendingCount.csv
sed -i s/MUMARLCGNA/Mumbai-BM/g   ${log}Brief_${DAY}_PendingCount.csv
sed -i s/VIKC/Vikhroli/g           ${log}Brief_${DAY}_PendingCount.csv
sed -i s/bankarcgna/BAN/g          ${log}Brief_${DAY}_PendingCount.csv
sed -i s/KARHBLNCL0/HUBLI/g        ${log}Brief_${DAY}_PendingCount.csv
sed -i s/upelkoncl-/UPE-LKO/g      ${log}Brief_${DAY}_PendingCount.csv
sed -i s/UPEVARNCL0/UPE-VARANASI/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/ROBASNNCL0/ROB-Asansol/g  ${log}Brief_${DAY}_PendingCount.csv
sed -i s/ROBBRHNCL0/ROB-Bahrampur/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/invimp03jb/Jabalpur/g ${log}Brief_${DAY}_PendingCount.csv
sed -i s/COIMATCGNA/Coimbatore/g ${log}Brief_${DAY}_PendingCount.csv

