DPATH=/CGFBKUPEXT3/E2ERECON/CHECKFILES
SPATH=/CGFBKUPEXT3/E2ERECON
TODAY=`date -d 'now -0 days' '+%Y%m%d'`
YDAY=`date -d 'now -2 days' '+%Y%m%d'`
a=`date -d 'now -0 days' '+%Y'`
a1=`date -d 'now -2 Hour' '+%Y%m%d'`
b=`date -d 'now -0 days' '+%m'`
c=`date -d 'now -0 days' '+%d'`
HH=`date -d 'now -2 Hour' '+%H'`

echo -e "<--table InterfaceStats starts-->" >$SPATH/OUTPUT-RECON.txt
echo "Hour,RA-GGSN,MED-GGSN,RA-PGW,MED-PGW,RA-SGW,MED-SGW,MED-MAHGGSN,MED-GUJGGSN,MED-RAJGGSN,MED-MPGGSN,TOTAL-RA,TOTAL-MED,DIFF-RA-MED">>$SPATH/OUTPUT-RECON.txt
#for (( i=00; i<=$HH; i++))
for i in {00..23}
do
if [ $HH == $i ]
then
echo -e "<--table InterfaceStats ends-->" >>$SPATH/OUTPUT-RECON.txt
mkdir -p $SPATH/$YDAY
mv $SPATH/*$YDAY*.log $SPATH/$YDAY/
exit 0
fi
HRAPGW=`cat /CGFBKUPEXT3/E2ERECON/R*RA*.log | grep PGW | awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`
HRAGGSN=`cat /CGFBKUPEXT3/E2ERECON/R*RA*.log | grep -v "PGW" | grep -v "SGW" | awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`
HRASGW=`cat /CGFBKUPEXT3/E2ERECON/R*RA*.log | grep SGW  | awk -F ',' '{print$2}' | grep $a1$i |  sort | uniq |  wc -l`

HMEDPGW=`cat /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep -v "I" |  awk -F ',' '{print$2}' |  grep $a1$i | sort | uniq | wc -l`
HMEDGGSN=`cat /CGFBKUPEXT3/E2ERECON/D8*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D71*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log |  awk -F ',' '{print$2}'| grep $a1$i | sort | uniq | wc -l`
HMEDSGW=`cat /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep "I"  |   awk -F ',' '{print$2}' | grep $a1$i | sort | uniq |  wc -l`


HMAHGGSN=`cat /CGFBKUPEXT3/E2ERECON/D8*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D71*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep -v "I" | grep MAH |  awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`
HGUJGGSN=`cat /CGFBKUPEXT3/E2ERECON/D8*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D71*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep -v "I" | grep GUJ |  awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`
HRAJGGSN=`cat /CGFBKUPEXT3/E2ERECON/D8*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D71*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep -v "I" | grep RAJ |  awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`
HMPGGSN=`cat /CGFBKUPEXT3/E2ERECON/D8*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D71*MED*.log /CGFBKUPEXT3/E2ERECON/D77*MED*.log /CGFBKUPEXT3/E2ERECON/D69*MED*.log /CGFBKUPEXT3/E2ERECON/D75*MED*.log | grep -v "I" | grep MPY |  awk -F ',' '{print$2}' | grep $a1$i | sort | uniq | wc -l`


HRA=`expr $HRAPGW + $HRAGGSN + $HRASGW`
HMED=`expr $HMEDPGW + $HMEDGGSN + $HMEDSGW`
DIFFRAMED=`expr $HRA - $HMED`
DIFFRAJMP=`expr $HMPGGSN - $HRAJGGSN`
echo "$i,$HRAGGSN,$HMEDGGSN,$HRAPGW,$HMEDPGW,$HRASGW,$HMEDSGW,$HMAHGGSN,$HGUJGGSN,$HRAJGGSN,$HMPGGSN,$HRA,$HMED,$DIFFRAMED">>$SPATH/OUTPUT-RECON.txt
TOTALHRAPGW=`expr $TOTALHRAPGW + $HRAPGW`
TOTALHRASGW=`expr $TOTALHRASGW + $HRASGW`
TOTALHRAGGSN=`expr $TOTALHRAGGSN + $HRAGGSN`

TOTALHMEDPGW=`expr $TOTALHMEDPGW + $HMEDPGW`
TOTALHMEDSGW=`expr $TOTALHMEDSGW + $HMEDSGW`
TOTALHMEDGGSN=`expr $TOTALHMEDGGSN + $HMEDGGSN`
TOTALRA=`expr $TOTALRA + $HRA`
TOTALMED=`expr $TOTALMED + $HMED`
TOTALDIIFEAMED=`expr $TOTALDIIFEAMED + $DIFFRAMED`

TOTALDIFFRAJMP=`expr $TOTALDIFFRAJMP + $DIFFRAJMP`
TOTALHMAHGGSN=`expr $TOTALHMAHGGSN + $HMAHGGSN`
TOTALHGUJGGSN=`expr $TOTALHGUJGGSN + $HGUJGGSN`
TOTALHRAJGGSN=`expr $TOTALHRAJGGSN + $HRAJGGSN`
TOTALHMPGGSN=`expr $TOTALHMPGGSN + $HMPGGSN`
done

echo "TOTAL,$TOTALHRAGGSN,$TOTALHMEDGGSN,$TOTALHRAPGW,$TOTALHMEDPGW,$TOTALHRASGW,$TOTALHMEDSGW,$TOTALHMAHGGSN,$TOTALHGUJGGSN,$TOTALHRAJGGSN,$TOTALMPGGSN,$TOTALRA,$TOTALMED,$TOTALDIIFEAMED,$TOTALDIFFRAJMP">>$SPATH/OUTPUT-RECON.txt
echo -e "<--table InterfaceStats ends-->" >>$SPATH/OUTPUT-RECON.txt
mkdir -p $SPATH/$YDAY
mv $SPATH/*$YDAY*.log $SPATH/$YDAY/